name: flix_id
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cloud_firestore: ^5.6.9
  cupertino_icons: ^1.0.8
  firebase_app_check: ^0.3.2+7
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  firebase_storage: ^12.4.7
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.0.0
  go_router: ^15.2.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  page_transition: ^2.2.1
  path: ^1.9.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  flutter_gen_runner: ^5.10.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/

flutter_gen:
  output: lib/gen/
  line_length: 80
